
train_file:  ['../../new_dataset/IC/last_train.json']

val_file: {'ch': '../../new_dataset/IC/new_val.json'}

test_file: {'ch': '../../new_dataset/IC/new_test.json'}

image_root: '../../pics/'

## Vision Encoder
use_beit_v2: True
vision_config: 'configs/config_beit2_base.json'
# vision_config: 'configs/config_beit2_large.json'

# image_res: 768
# patch_size: 16
image_res: 384
patch_size: 16
# image_res: 384
# patch_size: 32


model_type: 'CrossViewLM'
text_encoder: 'data/xlm-roberta-base'
text_num_hidden_layers: 12
cross_encoder: 'data/bert-base-uncased'
cross_num_hidden_layers: 6

text_fusion_start_at: 12

## Training
# use_one_cl_proj_only: False

embed_dim: 256
temp: 0.07

batch_size_train: 32
batch_size_test: 2
batch_size_test_text: 2
max_tokens: 40
# embed_dim: 256
# temp: 0.07
k_test: 80
# k_test: 4
accumulate_steps: 4


## Other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2, vision_lr: 2e-5, text_lr: 4e-5}
schedular: {sched: linear, epochs: 10, num_warmup_steps: 0.1}

