

train_file:  ['../../new_dataset/IC/last_train.json']

val_file: {'ch': '../../new_dataset/IC/new_val.json'}

test_file: {'ch': '../../new_dataset/IC/new_test.json'}


image_root: '../../pics'
## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32


## Text Encoder (& Cross Encoder)
text_encoder: 'data/xlm-roberta-large'
text_num_hidden_layers: 12



## Training
use_one_cl_proj_only: False

batch_size_train: 16
batch_size_test: 16
batch_size_test_text: 16
max_tokens: 40
embed_dim: 256
temp: 0.07
# k_test: 256
k_test: 80
accumulate_steps: 8



## Other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 10, num_warmup_steps: 0.1}

