train_file: ['../../new_dataset/VQA/new_VQA_train.json',]
valid_file: ['../../new_dataset/VQA/new_VQA_val.json']

answer_list: '../../new_dataset/VQA/answer_list.json'
vqa_root: '../../pics/'


# zero-shot test set

test_file: {
  'ch': [ '../../new_dataset/VQA/new_VQA_test.json',
        '../../new_dataset/VQA/new_VQA_test.json' ],
}



## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 768
patch_size: 16


## Text Encoder (& Cross Encoder)
text_encoder: 'data/xlm-roberta-large'
text_num_hidden_layers: 12


## Training
num_dec_layers: 6
batch_size_train: 16
batch_size_test: 4
max_tokens: 40
k_test: 128
accumulate_steps: 8



## Other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 5, num_warmup_steps: 0.1}
start_eval: 0  # epoch index


